# Generated by Django 4.0.5 on 2022-06-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_account',
            field=models.IntegerField(default=0, verbose_name='Тип аккаунта'),
        ),
    ]
