# Generated by Django 4.0.5 on 2022-06-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_type_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=15, verbose_name='номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(default='', max_length=300, verbose_name='telegram'),
            preserve_default=False,
        ),
    ]
