# Generated by Django 4.0.5 on 2022-06-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_description_user_phone_user_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватарка'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.TextField(blank=True, null=True, verbose_name='Статус'),
        ),
    ]
