# Generated by Django 4.0.5 on 2022-06-11 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internevent',
            name='contacts',
            field=models.ManyToManyField(blank=True, null=True, to='events.contact', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='internevent',
            name='date_end_request',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания приема заявок'),
        ),
        migrations.AlterField(
            model_name='internevent',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Учатсники'),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='bisness_needed',
            field=models.TextField(blank=True, null=True, verbose_name='Нам необходимо от бизнесса'),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='contacts',
            field=models.ManyToManyField(blank=True, null=True, to='events.contact', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='date_end_request',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания приема заявок'),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='date_event',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата мероприятия'),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Учатсники'),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='personal_needed',
            field=models.TextField(blank=True, null=True, verbose_name='Вам необходимо иметь c собой'),
        ),
    ]
