# Generated by Django 4.0.5 on 2022-06-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_internevent_contacts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Хештеги'},
        ),
    ]
