# Generated by Django 4.0.5 on 2022-06-11 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_alter_contact_options_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.AlterField(
            model_name='internevent',
            name='contacts',
            field=models.ManyToManyField(to='events.contact', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='internevent',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Учатсники'),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='contacts',
            field=models.ManyToManyField(to='events.contact', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Учатсники'),
        ),
    ]
