# Generated by Django 4.0.5 on 2022-06-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_skill_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internevent',
            name='skills',
            field=models.ManyToManyField(to='events.skill', verbose_name='Необходимые навыки'),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='skills',
            field=models.ManyToManyField(to='events.skill', verbose_name='Необходимые навыки'),
        ),
    ]
