# Generated by Django 4.0.5 on 2022-06-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_internevent_skills_alter_volunteerevent_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerevent',
            name='motivation',
            field=models.TextField(blank=True, null=True, verbose_name='Вы получите от волонтерства'),
        ),
    ]
