# Generated by Django 4.0.5 on 2022-06-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_volunteerevent_motivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='FF0000', max_length=6, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='internevent',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='volunteerevent',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Изображение'),
        ),
    ]
