# Generated by Django 4.0.5 on 2022-06-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_volunteerevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metro',
            name='color',
            field=models.CharField(default='FF0000', max_length=6, verbose_name='Цвет'),
        ),
    ]
