name: Django Deploy CD
on:
  push:
    branches: [backend]
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy to server
        if: ${{ !env.ACT }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BACKEND_IP }}
          username: ${{ secrets.BACKEND_USER }}
          key: ${{ secrets.BACKEND_USERKEY }}
          script: |
            docker-compose down 
            docker-compose up --build -d