name: Django Deploy CD

on:
  push:
    branches: [ backend ]
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BACKEND_IP }}
          username: ${{ secrets.BACKEND_USER }}
          key: ${{ secrets.BACKEND_USERKEY }}
          script: |
            docker-compose down 
            docker-compose up --build -d
