name: Django Deploy CD

on:
  push:
    branches: [ backend ]
  pull_request:
    branches: [ main ]
jobs:
  build:

      runs-on: ubuntu-latest
      strategy:
        max-parallel: 2
        matrix:
          python-version: [3.9, 3.10]

      steps:
      - uses: actions/checkout@v2
        with:
          ref: backend
      - name: Run docker
        run: |
          docker-compose up -d --build
  deploy:
  
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BACKEND_IP }}
          username: ${{ secrets.BACKEND_USER }}
          key: ${{ secrets.BACKEND_USERKEY }}
          script: |
            docker-compose down 
            docker-compose up --build -d
