name: Django Deploy CD

on:
  push:
    branches: [ backend ]
    
  workflow_dispatch:
    
jobs:
  build:

      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with:
          ref: backend
      - name: Run docker
        run: |
          docker-compose -f backend/docker-compose.yml up -d --build
  deploy:
  
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: cross-the-world/ssh-pipeline@v1.2.0
        with:
          user: ${{ secrets.USER }}
          host: ${{ secrets.BACKEND_IP }}
          key: ${{ secrets.USERKEY }}
          port: 22
          script: |
            docker-compose -f backend/docker-compose.yml up -d --build
