name: Django Deploy CD

on:
  push:
    branches: [ backend ]
    
  workflow_dispatch:
    
jobs:
  build:

      runs-on: ubuntu-latest
      strategy:
        max-parallel: 1
        matrix:
          python-version: [3.9]

      steps:
      - uses: actions/checkout@v2
        with:
          ref: backend
      - name: Run docker
        run: |
          docker-compose -f backend/docker-compose.yml up -d --build
  deploy:
  
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: matiasnu/github-action-ssh-docker-compose@v2.0.1
        with:
            # Private SSH key used for logging into remote system.
            ssh_private_key: ${{ secrets.USERKEY }}
            # Remote host name.
            ssh_host: ${{ secrets.BACKEND_IP }}
            # Remote user name.
            ssh_user: ${{ secrets.USER }}
            # Prefix for docker-compose containers.
            docker_compose_prefix: threads
            # Docker compose file to use
            docker_compose_filename: backend/docker-compose.yml
