name: Django Deploy CD

on:
  push:
    branches: [ backend ]
    
  workflow_dispatch:
    
jobs:
  build:

      runs-on: ubuntu-latest
      strategy:
        max-parallel: 1
        matrix:
          python-version: [3.9]

      steps:
      - uses: actions/checkout@v2
        with:
          ref: backend
      - name: Run docker
        run: |
          docker-compose -f backend/docker-compose.yml up -d --build
  deploy:
  
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: pcjun97/action-setup-docker-host-ssh@v1
        with:
          host: ${{ secrets.BACKEND_IP }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.USERKEY }}
          script: |
            docker-compose -f backend/docker-compose.yml up -d --build
