# Generated by Django 4.0.5 on 2022-06-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_volunteerevent_motivation'),
        ('community', '0002_alter_command_options_alter_friendship_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='tags',
        ),
        migrations.AddField(
            model_name='command',
            name='tags',
            field=models.ManyToManyField(related_name='commands', to='events.tag', verbose_name='Хештег'),
        ),
    ]
